#Python script to generate a ForceField file for moltemplate.

#Writing file
f = open("forcefield.lt", "w+")
f.write("ForceField {\n")
f.write("\n")
f.write("write_once(\"In Init\") {\n")
f.write("    units        lj\n")
f.write("    atom_style   angle\n")
f.write("    bond_style   harmonic\n")
f.write("    angle_style  harmonic\n")
f.write("    pair_style   hybrid/overlay dpd/tstat 1.0 1.0 2.5 34387 lj/cut 2.5\n")
f.write("}\n")
f.write("\n")
f.write("write_once(\"Data Masses\") {\n")
f.write("    @atom:P      1.0\n")
f.write("}\n")
f.write("write_once(\"In Settings\") {\n")
f.write("    #           atomType1 atomType2 Epsilon Sigma\n")
f.write("    pair_coeff  @atom:P   @atom:P   1.0     1.0\n")
f.write("}\n")
f.write("write_once(\"In Settings\") {\n")
f.write("    #           atomType1 atomType2 Epsilon Sigma\n")
f.write("    pair_coeff  @atom:P   @atom:P   1.0     1.0\n")
f.write("}\n")
f.write("write_once(\"In Settings\") {\n")
f.write("    #           bondType k     r0\n")
f.write("    bond_coeff  @bond:B  500.0 1.0\n")
f.write("}\n")
f.write("write_once(\"Data Angles By Type\") {\n")
f.write("    @angle:A  @atom:P  @atom:P  @atom:P  @bond:*  @bond:*\n")
f.write("}\n")
f.write("write_once(\"In Settings\") {\n")
f.write("    #           angleType k     theta0\n")
f.write("    angle_coeff  @angle:A  500.0 180.0\n")
f.write("}\n")
f.write("}\n")
